import type { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    name: 'Basic Training',
    spawnRate: 2000,
    scrollSpeed: 2,
    bulletSpeed: 3,
    enemyHpMultiplier: 1,
    enemyTypes: ['green'],
    hasBoss: true,
    bossType: 'bomber',
    targetScore: 1000,
  },
  {
    level: 2,
    name: 'The Squadron',
    spawnRate: 1500,
    scrollSpeed: 2,
    bulletSpeed: 3,
    enemyHpMultiplier: 1.2,
    enemyTypes: ['green', 'green'],
    hasBoss: false,
    targetScore: 2500,
  },
  {
    level: 3,
    name: 'Bullet Hell Intro',
    spawnRate: 1200,
    scrollSpeed: 3,
    bulletSpeed: 4,
    enemyHpMultiplier: 1.5,
    enemyTypes: ['green', 'red'],
    hasBoss: false,
    targetScore: 4000,
  },
  {
    level: 4,
    name: 'Heavy Armor',
    spawnRate: 1000,
    scrollSpeed: 3,
    bulletSpeed: 4,
    enemyHpMultiplier: 1.8,
    enemyTypes: ['green', 'red', 'tank'],
    hasBoss: false,
    targetScore: 5500,
  },
  {
    level: 5,
    name: 'Sky Fortress',
    spawnRate: 800,
    scrollSpeed: 4,
    bulletSpeed: 5,
    enemyHpMultiplier: 2,
    enemyTypes: ['green', 'red', 'tank'],
    hasBoss: true,
    bossType: 'bomber',
    targetScore: 7000,
  },
  {
    level: 6,
    name: 'Crossfire',
    spawnRate: 800,
    scrollSpeed: 4,
    bulletSpeed: 5,
    enemyHpMultiplier: 2.2,
    enemyTypes: ['red', 'tank', 'dive'],
    hasBoss: false,
    targetScore: 9000,
  },
  {
    level: 7,
    name: 'Swarm',
    spawnRate: 700,
    scrollSpeed: 5,
    bulletSpeed: 6,
    enemyHpMultiplier: 2.5,
    enemyTypes: ['green', 'red', 'dive'],
    hasBoss: false,
    targetScore: 11000,
  },
  {
    level: 8,
    name: 'Iron Rain',
    spawnRate: 600,
    scrollSpeed: 5,
    bulletSpeed: 6,
    enemyHpMultiplier: 3,
    enemyTypes: ['tank', 'tank', 'red'],
    hasBoss: false,
    targetScore: 13000,
  },
  {
    level: 9,
    name: 'No Fly Zone',
    spawnRate: 500,
    scrollSpeed: 5,
    bulletSpeed: 7,
    enemyHpMultiplier: 3.5,
    enemyTypes: ['red', 'tank', 'dive', 'dive'],
    hasBoss: false,
    targetScore: 15000,
  },
  {
    level: 10,
    name: 'Sky Dominance',
    spawnRate: 400,
    scrollSpeed: 6,
    bulletSpeed: 8,
    enemyHpMultiplier: 4,
    enemyTypes: ['green', 'red', 'tank', 'dive'],
    hasBoss: true,
    bossType: 'ace',
    targetScore: 18000,
  },
];

export const ENDLESS_LEVEL: LevelConfig = {
  level: 99,
  name: 'Endless Mode',
  spawnRate: 350,
  scrollSpeed: 6,
  bulletSpeed: 8,
  enemyHpMultiplier: 5,
  enemyTypes: ['green', 'red', 'tank', 'dive'],
  hasBoss: false,
  targetScore: 999999,
};
